# Generated by Django 5.1.3 on 2024-11-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_conteudo_post_content_rename_data_post_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expiration',
            field=models.DateField(),
        ),
    ]
