# Generated by Django 5.1.3 on 2024-11-13 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_content_alter_post_id_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expiration',
            field=models.DateField(default=datetime.datetime(2025, 11, 13, 19, 45, 18, 540473, tzinfo=datetime.timezone.utc)),
        ),
    ]
